spring:
  application:
    name: javaadvance

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/test_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:SECRET}

  hibernate:
    ddl-auto: none

  liquibase:
    enabled: true



