spring:
  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true

logging:
  level:
    org.testcontainers: DEBUG

jwt:
  secret: my-super-secret-key-for-jwt-token-signing-minimum-256-bits
  access-token-expiration: 900000
  refresh-token-expiration: 604800000